name: Activity 1

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello, World!"

      - name: Validate student.json
        run: |
          test -f student.json
          echo "student.json found"

      - name: Show student info
        run: cat student.json
